public class getExchangesWrapper {
    public String exchange_id {get;set;}
    public String website {get;set;}
    public String name {get;set;}
    public String data_start {get;set;}
    public String data_end {get;set;}
    public String data_quote_start {get;set;}
    public String data_quote_end {get;set;}
    public String data_orderbook_start {get;set;}
    public String data_orderbook_end {get;set;}
    public String data_trade_start {get;set;}
    public String data_trade_end {get;set;}
    public Integer data_symbols_count {get;set;}
    public Double volume_1hrs_usd {get;set;}
    public Double volume_1day_usd {get;set;}
    public Double volume_1mth_usd {get;set;}
}